name: Publish to Test PyPI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  test_pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
      - uses: "abatilo/actions-poetry@v2.0.0"
      - name: Configure poetry
        run: poetry config virtualenvs.in-project true
      - name: Install Dependencies
        run: poetry install
      - name: Publish package
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}
          poetry publish --build