name: Publish to PyPI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - uses: "abatilo/actions-poetry@v2.0.0"
      - name: Configure poetry
        run: poetry config virtualenvs.in-project true
      - name: Install Dependencies
        run: poetry install
      - name: Publish package
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_KEY }}
          poetry publish --build